# AUTOGENERATED FILE - DO NOT MODIFY!
# This file generated by Djinni from example.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files
from djinni.pycffi_marshal import CPyPrimitive, CPyRecord
from PyCFFIlib_cffi import ffi, lib

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

from a import A

class AHelper:
    @staticmethod
    def release(c_ptr):
        assert c_ptr in c_data_set
        c_data_set.remove(ffi.cast("void*", c_ptr))

    @ffi.callback("uint8_t(struct DjinniRecordHandle *)")
    def get_a_f1(cself):
        try:
            _ret = CPyPrimitive.fromPy(CPyRecord.toPy(None, cself).h)
            return _ret
        except Exception as _djinni_py_e:
            CPyException.setExceptionFromPy(_djinni_py_e)
            return ffi.NULL

    @ffi.callback("struct DjinniRecordHandle *(uint8_t)")
    def python_create_a(h):
        py_rec = A(
            CPyPrimitive.toPy(h))
        return CPyRecord.fromPy(A.c_data_set, py_rec) #to do: can be optional?

    @ffi.callback("void (struct DjinniRecordHandle *)")
    def __delete(dh):
        assert dh in A.c_data_set
        A.c_data_set.remove(dh)

    @staticmethod
    def _add_callbacks():
        lib.a_add_callback_python_create_a(AHelper.python_create_a)
        lib.a_add_callback_get_a_f1(AHelper.get_a_f1)
        lib.a_add_callback___delete(AHelper.__delete)

AHelper._add_callbacks()

